// Auto-generated by Scripts/fetch-erika.sh — do not edit by hand.
// 每次拉取内核时随 vendored 二进制一起重写，保证版本串不与本地内核漂移。

/// 当前 vendored 的 Erika 内核 release tag（如 "$TAG"）。
public enum ErikaVersion {
    public static let tag = "v0.1.9+dolby.streaming.dev"
}
